Add work with orders
VoitseshukV/bookstore pull request #12
Opened 2023-11-26 01:22 UTC by VoitseshukV

2023-11-27 11:42 UTC, okuzan requested changes

2023-11-27 11:42 UTC, okuzan commented on src/main/java/com/bookstore/core/model/Order.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE orders SET is_deleted = TRUE WHERE id=?")
@Where(clause = "is_deleted = FALSE")
```

2023-11-27 11:42 UTC, okuzan commented on src/main/java/com/bookstore/core/service/impl/OrderServiceImpl.java
> +        return null;
returning null is a bad practice, return updated Order

2023-11-27 11:42 UTC, okuzan commented on src/main/java/com/bookstore/core/service/impl/OrderServiceImpl.java
> +                () -> new EntityNotFoundException("Can't get user with email: " + email));
use service method for find/orElseThrow logic everywhere (create if needed)

2023-11-27 11:42 UTC, okuzan commented on src/main/java/com/bookstore/core/service/impl/OrderServiceImpl.java
> +        }
method is too bulky, delegate some logic to private methods

2023-11-28 12:41 UTC, Sanderfuck approved these changes

2023-11-28 12:41 UTC, Sanderfuck commented on src/main/java/com/bookstore/core/repository/order/OrderRepository.java
> +    Optional<Order> findFirstById(Long id);
Is it possible find second byId, by id exist must only one

2023-11-28 13:15 UTC, merged