add tests to classes Book, Category
VoitseshukV/bookstore pull request #14
Opened 2023-11-29 19:25 UTC by VoitseshukV

2023-11-29 19:27 UTC, VoitseshukV commented
![2023-11-29 21_19_38](https://github.com/VoitseshukV/bookstore/assets/67281752/46fa05fc-8834-4105-88d0-3bb716cce5ff)

2023-11-30 10:15 UTC, Sanderfuck requested changes

2023-11-30 10:15 UTC, Sanderfuck commented on src/test/java/com/bookstore/core/repository/BookRepositoryTest.java
> +                .setPrice(BigDecimal.valueOf(420)));
You can make templates of books and reuse it where it needs

2023-11-30 10:15 UTC, Sanderfuck commented on src/test/java/com/bookstore/core/repository/BookRepositoryTest.java
> +
```suggestion
```

2023-12-01 10:52 UTC, okuzan approved these changes

2023-12-01 11:31 UTC, merged